using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace basket_compair
{
    public class Vehicle
    {
        public string vehicle_id { get; set; }
        public string uid { get; set; }
        public double overall_length { get; set; }
        public double overall_width { get; set; }
        public double overall_height { get; set; }
        public string powertrain_type { get; set; }
        public string fuel_type { get; set; }
        public string retail_price { get; set; }
        public string base_price { get; set; }
        public string research_date { get; set; }
        public string data_date { get; set; }
        public string conclude_date { get; set; }
        public string model_year { get; set; }
        public string number_of_speakers { get; set; }
        public string brand_name { get; set; }
        public string subwoofer { get; set; }
        public string surround_sound { get; set; }
        public string in_dash_cd { get; set; }
        public string digital_media_card { get; set; }
        public string internet_radio { get; set; }
        public string touch_screen { get; set; }
        public string remote_audio_controls { get; set; }
        public string disc_player { get; set; }
        public string ipod_front { get; set; }
        public string aux_jack_front { get; set; }
        public string usb_connection_front { get; set; }
        public string hdmi_connection_front { get; set; }
        public string aux_jack_rear { get; set; }
        public string usb_connection_rear { get; set; }
        public string ipod_rear { get; set; }
        public string hdmi_connection_rear { get; set; }
        public string around_side_windows { get; set; }
        public string electronic_hand_brake { get; set; }
        public string hill_holder { get; set; }
        public string cargo_area_cover_type { get; set; }
        public string load_restraint_sliding_anchorage_points { get; set; }
        public string j12v_power_number_of_outlets { get; set; }
        public string electric_trunk_hatch_pull_down { get; set; }
        public string door_mirror_position { get; set; }
        public string rearview_mirror { get; set; }
        public string cruise_control { get; set; }
        public string adaptive_cruise_control { get; set; }
        public string stop_go_function { get; set; }
        public string adaptive_cruise_cont_linked_to_mapping { get; set; }
        public string vanity_mirror_illuminated { get; set; }
        public string parking_distance_system_location { get; set; }
        public string type_1 { get; set; }
        public string navigational_systems { get; set; }
        public string information_type { get; set; }
        public string data_feed { get; set; }
        public string screen_size_in { get; set; }
        public string traffic_info { get; set; }
        public string traffic_information { get; set; }
        public string screen_location { get; set; }
        public string digital_television { get; set; }
        public string dual_view_screen { get; set; }
        public string smart_card_type { get; set; }
        public string includes_keyless_entry { get; set; }
        public string includes_keyless_start { get; set; }
        public string includes_memory_seat_adjustments { get; set; }
        public string includes_programmable_settings { get; set; }
        public string includes_audio_player { get; set; }
        public string includes_phone { get; set; }
        public string includes_navigation_system { get; set; }
        public string includes_air_conditioning { get; set; }
        public string virtual_assistant { get; set; }
        public string internet_connection { get; set; }
        public string advanced_auto_collision_notification { get; set; }
        public string connection_type { get; set; }
        public string tracker_system { get; set; }
        public string breakdown_assistance { get; set; }
        public string blind_junction_view { get; set; }
        public string includes_phone_connection { get; set; }
        public string includes_music_streaming { get; set; }
        public string parking_assistance_type { get; set; }
        public string automatic_braking_whilst_parking { get; set; }
        public string speed_limiter { get; set; }
        public string j360_view_camera { get; set; }
        public string trailer_reversing_aid { get; set; }
        public string trailer_hitch_assist { get; set; }
        public string trailer_brake_control { get; set; }
        public string connectivity_type { get; set; }
        public string includes_battery_status_checking { get; set; }
        public string includes_remote_charge_activation { get; set; }
        public string includes_charge_completion_alert { get; set; }
        public string remote_air_conditioning_control { get; set; }
        public string includes_heating { get; set; }
        public string includes_cooling { get; set; }
        public string wireless_charging_pad { get; set; }
        public string rear_cross_traffic_alert { get; set; }
        public string hands_free_boot_release { get; set; }
        public string facial_gesture_control_location { get; set; }
        public string text_to_speech_speech_to_text { get; set; }
        public string apple_carplay { get; set; }
        public string android_auto { get; set; }
        public string mirrorlink { get; set; }
        public string apple_wireless_connection { get; set; }
        public string android_wireless_connection { get; set; }
        public string front_cross_traffic_alert { get; set; }
        public string usb_charging_port_number { get; set; }
        public string instrument_panel_type { get; set; }
        public string head_up_display { get; set; }
        public string reconfigurable { get; set; }
        public string range_for_remaining_fuel { get; set; }
        public string displays_pressure { get; set; }
        public string traffic_sign_recognition { get; set; }
        public string on_shift_knob { get; set; }
        public string on_center_floor_console { get; set; }
        public string on_doors { get; set; }
        public string on_instrument_panel { get; set; }
        public string on_handbrake_grip { get; set; }
        public string floor_mats { get; set; }
        public string type_2 { get; set; }
        public string door_sill_protector_illuminated { get; set; }
        public string bulb_type_low_beam { get; set; }
        public string bulb_type_high_beam { get; set; }
        public string dusk_sensor { get; set; }
        public string auto_highbeam { get; set; }
        public string directional_headlights { get; set; }
        public string active_high_beam { get; set; }
        public string matrix { get; set; }
        public string front_fog_lights { get; set; }
        public string cornering_lights_curb_illumination { get; set; }
        public string location_1 { get; set; }
        public string power_locks { get; set; }
        public string operation_1 { get; set; }
        public string includes_power_windows { get; set; }
        public string includes_dead_bolt { get; set; }
        public string anti_theft_protection { get; set; }
        public string interior_monitoring { get; set; }
        public string paint_type { get; set; }
        public string multi_coat { get; set; }
        public string two_tone_1 { get; set; }
        public string sunroof_location { get; set; }
        public string type_3 { get; set; }
        public string operation_2 { get; set; }
        public string roof_rails { get; set; }
        public string cross_bars { get; set; }
        public string colour { get; set; }
        public string glass_roof { get; set; }
        public string occupant_switch_off { get; set; }
        public string intelligent { get; set; }
        public string side_airbag_location { get; set; }
        public string active_1 { get; set; }
        public string height_adjustable_1 { get; set; }
        public string seat_position { get; set; }
        public string pre_tensioners { get; set; }
        public string height_adjustable_2 { get; set; }
        public string overtaking_sensor { get; set; }
        public string includes_collision_avoidance { get; set; }
        public string knee_airbags_location { get; set; }
        public string anti_collision_system { get; set; }
        public string activates_seat_belts { get; set; }
        public string activates_brake_lights { get; set; }
        public string driver_monitor { get; set; }
        public string automatic_emergency_braking { get; set; }
        public string brakes_at_low_speed { get; set; }
        public string pedestrian___cyclist_avoidance_system { get; set; }
        public string lane_departure_warning { get; set; }
        public string activates_brakes { get; set; }
        public string activates_steering { get; set; }
        public string rear_screen_airbag { get; set; }
        public string rear_seat_belt_inflatable { get; set; }
        public string rear_seat_centre_airbag { get; set; }
        public string dynamic_steering { get; set; }
        public string front_seats_centre_airbag { get; set; }
        public string multi_collision_braking { get; set; }
        public string seating_capacity { get; set; }
        public string main_seat_material { get; set; }
        public string additional_seat_material { get; set; }
        public string front_seat_center_armrest { get; set; }
        public string rear_seat_center_armrest { get; set; }
        public string type_4 { get; set; }
        public string heated_1 { get; set; }
        public string seat_folds_to_table { get; set; }
        public string active_massage { get; set; }
        public string ventilated_1 { get; set; }
        public string climate_controlled { get; set; }
        public string folding_1 { get; set; }
        public string reclining_type_1 { get; set; }
        public string reach_type_1 { get; set; }
        public string height_type_1 { get; set; }
        public string lumbar_type { get; set; }
        public string tilt_type { get; set; }
        public string thigh_support_type { get; set; }
        public string rear_seats_type { get; set; }
        public string heated_2 { get; set; }
        public string folding_2 { get; set; }
        public string ventilated_2 { get; set; }
        public string reclining_type_2 { get; set; }
        public string reach_type_2 { get; set; }
        public string ski_hatch { get; set; }
        public string remote_folding_1 { get; set; }
        public string folds_electrically_1 { get; set; }
        public string third_row_seats_removable { get; set; }
        public string fold_flat_to_floor { get; set; }
        public string folds_electrically_2 { get; set; }
        public string remote_folding_2 { get; set; }
        public string steering_wheels_type { get; set; }
        public string sports { get; set; }
        public string telescopic_adjustment { get; set; }
        public string electric_adjustment { get; set; }
        public string heated_3 { get; set; }
        public string multi_function { get; set; }
        public string vehicle_speed_proportional { get; set; }
        public string refrigerated_storage_compartment { get; set; }
        public string below_seat_storage_location { get; set; }
        public string spring_type { get; set; }
        public string suspension_levelling { get; set; }
        public string responsive_suspension_type { get; set; }
        public string driven_wheels_1 { get; set; }
        public string descent_control_system { get; set; }
        public string differential_lock { get; set; }
        public string limited_slip_differential { get; set; }
        public string transmission_description { get; set; }
        public string stability_control { get; set; }
        public string terrain_type_selection { get; set; }
        public string includes_tr_esp_adjustment { get; set; }
        public string automatic_recirculation { get; set; }
        public string air_conditioning { get; set; }
        public string rear_control_for_climate_control { get; set; }
        public string climate_control_number_of_zones { get; set; }
        public string air_conditioning_type { get; set; }
        public string version_state { get; set; }
        public string data_status { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string local_make_name { get; set; }
        public string local_model_name { get; set; }
        public string model_descriptor { get; set; }
        public string local_version_name { get; set; }
        public string version_name { get; set; }
        public string trim_level { get; set; }
        public string local_trim_level { get; set; }
        public string number_of_doors { get; set; }
        public string location_2 { get; set; }
        public string type_5 { get; set; }
        public string auto_dimming_1 { get; set; }
        public string door_mirror_cameras_type { get; set; }
        public string heated_4 { get; set; }
        public string tilting_for_reversing { get; set; }
        public string auto_dimming_2 { get; set; }
        public string foldable_mirrors_elec_or_mechanical { get; set; }
        public string rain_sensor { get; set; }
        public string electrically_heated_windshield { get; set; }
        public string power_windows_location { get; set; }
        public string number_of_express { get; set; }
        public string heated_washer { get; set; }
        public string privacy_glass { get; set; }
        public string location_3 { get; set; }
        public string run_flat { get; set; }
        public string self_sealing_tires { get; set; }
        public string rim_type { get; set; }
        public string rim_diameter_in { get; set; }
        public string two_tone { get; set; }
        public string structure_wheel { get; set; }
        public string bodystyle { get; set; }
        public string wheelbase_type { get; set; }
        public string driven_wheels_2 { get; set; }
        public string transmission_type { get; set; }
        public string liters { get; set; }
        public string max_power_kw { get; set; }
        public string max_power_hp_ps { get; set; }
        public string compressor { get; set; }
        public string spare_wheel_type { get; set; }
    }
}
